// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million(4,000,000), find the sum of the even-valued terms.

class Problem2{
  public static void main(String[] args) {
    long counter=0;
    long result=0;
    long number1=1;
    long number2=0;
    long number3=0;

    while(number2<4000000){
      if(number2%2==0)
        result += number2;
      number3=number1+number2;
      number1=number2;
      number2=number3;
      counter++;
    }
    System.out.println(result);
  }

}
